CREATE TABLE `rececoes_materias_primas` (
  `id` int AUTO_INCREMENT NOT NULL,
  `fabrica_id` int NOT NULL,
  `armazem` enum('ambiente_secos','frio','embalagens') NOT NULL,
  `data_rececao` timestamp NOT NULL,
  `fornecedor_id` int NOT NULL,
  `materia_prima_id` int NOT NULL,
  `validade` date,
  `lote` varchar(100),
  `quantidade` float NOT NULL,
  `unidade` enum('kg','g','l','un','caixa','saco','palete','bigbag') NOT NULL DEFAULT 'kg',
  `controlos` json,
  `conformidade` enum('conforme','nao_conforme','pendente') NOT NULL DEFAULT 'pendente',
  `numero_paletes_lpr` int,
  `responsavel` varchar(150) NOT NULL,
  `numero_guia` varchar(100),
  `observacoes` text,
  `motivo_nao_conformidade` text,
  `registado_por` int,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `rececoes_materias_primas_id` PRIMARY KEY(`id`),
  CONSTRAINT `rececoes_materias_primas_fabrica_id_fabricas_id_fk` FOREIGN KEY (`fabrica_id`) REFERENCES `fabricas`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `rececoes_materias_primas_fornecedor_id_fornecedores_id_fk` FOREIGN KEY (`fornecedor_id`) REFERENCES `fornecedores`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `rececoes_materias_primas_materia_prima_id_materias_primas_id_fk` FOREIGN KEY (`materia_prima_id`) REFERENCES `materias_primas`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `rececoes_materias_primas_registado_por_users_id_fk` FOREIGN KEY (`registado_por`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action
);
